import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/assets/styles/index.scss';
import { Header } from '@/layouts/Header/Header';
// import FaviconPng from '/public/favicon.png';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // icons: {
  //   icon: FaviconPng.src,
  //   apple: FaviconPng.src,
  // },
};

const geometria = localFont({
  src: [
    {
      path: './fonts/geometria/geometria_bold.otf',
      weight: '700',
      style: 'bold',
    },
    {
      path: './fonts/geometria/geometria_bolditalic.otf',
      weight: '700',
      style: 'italic',
    },
    {
      path: './fonts/geometria/geometria_extrabold.otf',
      weight: '800',
      style: 'bold',
    },
    {
      path: './fonts/geometria/geometria_light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/geometria/geometria_lightitalic.otf',
      weight: '300',
      style: 'italic',
    },
    {
      path: './fonts/geometria/geometria_medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/geometria/geometria_mediumitalic.otf',
      weight: '400',
      style: 'italic',
    },
  ],
});

type RootLayoutType = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutType) {
  return (
    <html lang='ru'>
      <body className={geometria.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
